export default defineEventHandler((event) => {
  return [
    {
      type: "Wheat Ears Reverse, Bronze V.D.B.",
      dates: "1909",
      rev: "/img/lincoln-vdb-reverse.jpg",
      issues: [
        { issue: "1909", variant: "V.D.B." },
        { issue: "1909", variant: "V.D.B., Matte Proof" },
        { issue: "1909-S", variant: "V.D.B." },
      ],
    },
    {
      type: "Wheat Ears Reverse, Bronze",
      dates: "1909-1942; 1944-1958",
      rev: "/img/lincoln-wheat-reverse.jpg",
      issues: [
        { issue: "1909" },
        { issue: "1909", variant: "Matte Proof" },
        { issue: "1909-S" },
        { issue: "1910" },
        { issue: "1910", variant: "Matte Proof" },
        { issue: "1910-S" },
        { issue: "1911" },
        { issue: "1911", variant: "Matte Proof" },
        { issue: "1911-D" },
        { issue: "1911-S" },
        { issue: "1912" },
        { issue: "1912", variant: "Matte Proof" },
        { issue: "1912-D" },
        { issue: "1912-S" },
        { issue: "1913" },
        { issue: "1913", variant: "Matte Proof" },
        { issue: "1913-D" },
        { issue: "1913-S" },
        { issue: "1914" },
        { issue: "1914", variant: "Matte Proof" },
        { issue: "1914-D" },
        { issue: "1914-S" },
        { issue: "1915" },
        { issue: "1915", variant: "Matte Proof" },
        { issue: "1915-D" },
        { issue: "1915-S" },
        { issue: "1916" },
        { issue: "1916", variant: "Matte Proof" },
        { issue: "1916-D" },
        { issue: "1916-S" },
        { issue: "1917" },
        { issue: "1917-D" },
        { issue: "1917-S" },
        { issue: "1918" },
        { issue: "1918-D" },
        { issue: "1918-S" },
        { issue: "1919" },
        { issue: "1919-D" },
        { issue: "1919-S" },
        { issue: "1920" },
        { issue: "1920-D" },
        { issue: "1920-S" },
        { issue: "1921" },
        { issue: "1921-S" },
        { issue: "1922-D" },
        { issue: "1923" },
        { issue: "1923-S" },
        { issue: "1924" },
        { issue: "1924-D" },
        { issue: "1924-S" },
        { issue: "1925" },
        { issue: "1925-D" },
        { issue: "1925-S" },
        { issue: "1926" },
        { issue: "1926-D" },
        { issue: "1926-S" },
        { issue: "1927" },
        { issue: "1927-D" },
        { issue: "1927-S" },
        { issue: "1928" },
        { issue: "1928-D" },
        { issue: "1928-S" },
        { issue: "1929" },
        { issue: "1929-D" },
        { issue: "1929-S" },
        { issue: "1930" },
        { issue: "1930-D" },
        { issue: "1930-S" },
        { issue: "1931" },
        { issue: "1931-D" },
        { issue: "1931-S" },
        { issue: "1932" },
        { issue: "1932-D" },
        { issue: "1933" },
        { issue: "1933-D" },
        { issue: "1934" },
        { issue: "1934-D" },
        { issue: "1935" },
        { issue: "1935-D" },
        { issue: "1935-S" },
        { issue: "1936" },
        { issue: "1936", variant: "Proof" },
        { issue: "1936-D" },
        { issue: "1936-S" },
        { issue: "1937" },
        { issue: "1937", variant: "Proof" },
        { issue: "1937-D" },
        { issue: "1937-S" },
        { issue: "1938" },
        { issue: "1938", variant: "Proof" },
        { issue: "1938-D" },
        { issue: "1938-S" },
        { issue: "1939" },
        { issue: "1939", variant: "Proof" },
        { issue: "1939-D" },
        { issue: "1939-S" },
        { issue: "1940" },
        { issue: "1940", variant: "Proof" },
        { issue: "1940-D" },
        { issue: "1940-S" },
        { issue: "1941", have: true },
        { issue: "1941", variant: "Proof" },
        { issue: "1941-D", have: true },
        { issue: "1941-S" },
        { issue: "1942", have: true },
        { issue: "1942", variant: "Proof" },
        { issue: "1942-D", have: true },
        { issue: "1942-S" },
        { issue: "1944", have: true },
        { issue: "1944-D", have: true },
        { issue: "1944-S" },
        { issue: "1945", have: true },
        { issue: "1945-D" },
        { issue: "1945-S", have: true },
        { issue: "1946", have: true },
        { issue: "1946-D", have: true },
        { issue: "1946-S" },
        { issue: "1947" },
        { issue: "1947-D", have: true },
        { issue: "1947-S" },
        { issue: "1948", have: true },
        { issue: "1948-D" },
        { issue: "1948-S" },
        { issue: "1949", have: true },
        { issue: "1949-D" },
        { issue: "1949-S" },
        { issue: "1950", have: true },
        { issue: "1950", variant: "Proof" },
        { issue: "1950-D", have: true },
        { issue: "1950-S" },
        { issue: "1951" },
        { issue: "1951", variant: "Proof" },
        { issue: "1951-D", have: true },
        { issue: "1951-S" },
        { issue: "1952", have: true },
        { issue: "1952", variant: "Proof" },
        { issue: "1952-D", have: true },
        { issue: "1952-S" },
        { issue: "1953", have: true },
        { issue: "1953", variant: "Proof" },
        { issue: "1953-D", have: true },
        { issue: "1953-S", have: true },
        { issue: "1954" },
        { issue: "1954", variant: "Proof" },
        { issue: "1954-D" },
        { issue: "1954-S" },
        { issue: "1955", have: true },
        { issue: "1955", variant: "Proof" },
        { issue: "1955-D", have: true },
        { issue: "1955-S" },
        { issue: "1956", have: true },
        { issue: "1956", variant: "Proof" },
        { issue: "1956-D", have: true },
        { issue: "1957", have: true },
        { issue: "1957", variant: "Proof" },
        { issue: "1957-D", have: true },
        { issue: "1958", have: true },
        { issue: "1958", variant: "Proof" },
        { issue: "1958-D", have: true },
      ],
    },
    {
      type: "Wheat Ears Reverse, Steel",
      dates: "1943",
      rev: "/img/lincoln-steel-reverse.jpg",
      issues: [
        { issue: "1943", have: true },
        { issue: "1943-D" },
        { issue: "1943-S" },
      ],
    },
    {
      type: "Memorial Reverse, Bronze",
      dates: "1959-1982",
      rev: "/img/lincoln-memorial-reverse.jpg",
      issues: [
        { issue: "1982", variant: "Large Date" },
        { issue: "1982", variant: "Small Date" },
        { issue: "1982-D", variant: "Large Date" },
        {
          issue: "1982-S",
          variant: "Small Date, Proof",
          rev: "/img/lincoln-memorial-reverse-proof.jpg",
        },
      ],
    },
    {
      type: "Memorial Reverse, Copper-Plated Zinc",
      dates: "1982-2008",
      rev: "/img/lincoln-memorial-reverse.jpg",
      issues: [
        { issue: "1982", variant: "Large Date" },
        { issue: "1982", variant: "Small Date" },
        { issue: "1982-D", variant: "Large Date" },
        { issue: "1982-D", variant: "Small Date" },
      ],
    },
    {
      type: "Bicentennial Reverse",
      dates: "2009",
      issues: [
        {
          issue: "2009",
          variant: "Birth and Early Childhood",
          have: true,
          rev: "/img/lincoln-bicentennial-birth.jpg",
        },
        {
          issue: "2009",
          variant: "Birth and Early Childhood, Copper",
          rev: "/img/lincoln-bicentennial-birth.jpg",
        },
        {
          issue: "2009-D",
          variant: "Birth and Early Childhood",
          rev: "/img/lincoln-bicentennial-birth.jpg",
        },
        {
          issue: "2009-D",
          variant: "Birth and Early Childhood, Copper",
          rev: "/img/lincoln-bicentennial-birth.jpg",
        },
        {
          issue: "2009-S",
          variant: "Birth and Early Childhood, Copper, Proof",
          rev: "/img/lincoln-bicentennial-birth.jpg",
        },
        {
          issue: "2009",
          variant: "Formative Years",
          rev: "/img/lincoln-bicentennial-youth.jpg",
        },
        {
          issue: "2009",
          variant: "Formative Years, Copper",
          rev: "/img/lincoln-bicentennial-youth.jpg",
        },
        {
          issue: "2009-D",
          variant: "Formative Years",
          rev: "/img/lincoln-bicentennial-youth.jpg",
        },
        {
          issue: "2009-D",
          variant: "Formative Years, Copper",
          rev: "/img/lincoln-bicentennial-youth.jpg",
        },
        {
          issue: "2009-S",
          variant: "Formative Years, Copper, Proof",
          rev: "/img/lincoln-bicentennial-youth.jpg",
        },
        {
          issue: "2009",
          variant: "Professional Life",
          rev: "/img/lincoln-bicentennial-professional-life.jpg",
        },
        {
          issue: "2009",
          variant: "Professional Life, Copper",
          rev: "/img/lincoln-bicentennial-professional-life.jpg",
        },
        {
          issue: "2009-D",
          variant: "Professional Life",
          rev: "/img/lincoln-bicentennial-professional-life.jpg",
        },
        {
          issue: "2009-D",
          variant: "Professional Life, Copper",
          rev: "/img/lincoln-bicentennial-professional-life.jpg",
        },
        {
          issue: "2009-S",
          variant: "Professional Life, Copper, Proof",
          rev: "/img/lincoln-bicentennial-professional-life.jpg",
        },
        {
          issue: "2009",
          variant: "Presidency",
          rev: "/img/lincoln-bicentennial-presidency.jpg",
        },
        {
          issue: "2009",
          variant: "Presidency, Copper",
          rev: "/img/lincoln-bicentennial-presidency.jpg",
        },
        {
          issue: "2009-D",
          variant: "Presidency",
          rev: "/img/lincoln-bicentennial-presidency.jpg",
        },
        {
          issue: "2009-D",
          variant: "Presidency, Copper",
          rev: "/img/lincoln-bicentennial-presidency.jpg",
        },
        {
          issue: "2009-S",
          variant: "Presidency, Copper, Proof",
          rev: "/img/lincoln-bicentennial-presidency.jpg",
        },
      ],
    },
    {
      type: "Shield Reverse",
      dates: "Since 2010",
      rev: "/img/lincoln-shield-reverse.jpg",
      issues: [
        { issue: "2010", have: true },
        { issue: "2010-D" },
        {
          issue: "2010-S",
          variant: "Proof",
          rev: "/img/lincoln-shield-reverse-proof.jpg",
        },
        { issue: "2011" },
        { issue: "2011-D" },
        {
          issue: "2011-S",
          variant: "Proof",
          rev: "/img/lincoln-shield-reverse-proof.jpg",
        },
        { issue: "2012", have: true },
        { issue: "2012-D" },
        {
          issue: "2012-S",
          variant: "Proof",
          rev: "/img/lincoln-shield-reverse-proof.jpg",
        },
        { issue: "2013", have: true },
        { issue: "2013-D", have: true },
        {
          issue: "2013-S",
          variant: "Proof",
          rev: "/img/lincoln-shield-reverse-proof.jpg",
        },
        { issue: "2014", have: true },
        { issue: "2014-D" },
        {
          issue: "2014-S",
          variant: "Proof",
          rev: "/img/lincoln-shield-reverse-proof.jpg",
        },
        { issue: "2015", have: true },
        { issue: "2015-D" },
        {
          issue: "2015-S",
          variant: "Proof",
          rev: "/img/lincoln-shield-reverse-proof.jpg",
        },
        { issue: "2016", have: true },
        { issue: "2016-D", have: true },
        {
          issue: "2016-S",
          variant: "Proof",
          rev: "/img/lincoln-shield-reverse-proof.jpg",
        },
        { issue: "2017-P", have: true },
        { issue: "2017-D", have: true },
        {
          issue: "2017-S",
          variant: "Proof",
          rev: "/img/lincoln-shield-reverse-proof.jpg",
        },
        { issue: "2018", have: true },
        { issue: "2018-D" },
        {
          issue: "2018-S",
          variant: "Proof",
          rev: "/img/lincoln-shield-reverse-proof.jpg",
        },
        { issue: "2019", have: true },
        { issue: "2019-D", have: true },
        {
          issue: "2019-S",
          variant: "Proof",
          rev: "/img/lincoln-shield-reverse-proof.jpg",
        },
        { issue: "2019-W" },
        {
          issue: "2019-W",
          variant: "Proof",
          have: true,
          rev: "/img/lincoln-shield-reverse-proof.jpg",
        },
        {
          issue: "2019-W",
          variant: "Reverse Proof",
          rev: "/img/lincoln-shield-reverse-proof-reverse.jpg",
        },
        { issue: "2020", have: true },
        { issue: "2020-D", have: true },
        {
          issue: "2020-S",
          variant: "Proof",
          rev: "/img/lincoln-shield-reverse-proof.jpg",
        },
        { issue: "2021", have: true },
        { issue: "2021-D", have: true },
        {
          issue: "2021-S",
          variant: "Proof",
          rev: "/img/lincoln-shield-reverse-proof.jpg",
        },
        { issue: "2022", have: true },
        { issue: "2022-D" },
        {
          issue: "2022-S",
          variant: "Proof",
          rev: "/img/lincoln-shield-reverse-proof.jpg",
        },
        { issue: "2023", have: true },
        { issue: "2023-D" },
        {
          issue: "2023-S",
          variant: "Proof",
          rev: "/img/lincoln-shield-reverse-proof.jpg",
        },
      ],
    },
  ];
});
